### ISSUE TITLE
USER STORY: Create landing page

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-co#27]
As a **Site User**, I can **arrive on a page where I can instantly identify the website I am on** so that **I know if I clicked right or not and eventually leave if it is not the page I intended to reach**.
As a **Site User**, I can **clearly identify the purpose of the website** so that **I know if it offers what I am looking for and therefore decide to stay or leave**.
As a **Site User**, I can **easily identify the navigation menu with explicit options** so that **I can easily guess where to click to find the information I am looking for**.
As a **Site Owner**, I can **invite users to take action** so that **I have more chances to transform them into customers**.

---
**Acceptance Criteria**
- [ ] **Given** , **when** , **then** .
    - [ ] the company branding format
    - [ ] a clear and explicit navigation menu
    - [ ] a footer
 
---
**Tasks**
- [ ] Create the content of the page
- [ ] Create the HTML & CSS
- [ ] Test the page:
    - [ ] Works properly when page not found
    - [ ] Display right content with right style on any type of devices
    - [ ] Display right content with right style on any web browser
