### ISSUE TITLE
USER STORY: Define the strategy

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-co#28]
As a **Stakeholder**, I can **find information about the business development strategy** so that **I am aware of how the website should be implemented**.

---
**Acceptance Criteria**
- [ ] **Given** that I am part of the development team, **when** I read the README file of the repository, **then** I find relevant information about how the website should be implemented.
 
---
**Tasks**
- [ ] Define website's primary goals
- [ ] Define the Marketing Business Story (what to offer, value it brings, how people get it)
- [ ] Define the target audience
    - [ ] Define the buyer persona
- [ ] Analyse the competition
- [ ] Define your branding, messaging and unique value proposition
- [ ] Look for Top-performing keywords in terms of rank, traffic, and lead generation
- [ ] Define the content
