### ISSUE TITLE
USER STORY: Implement 500 error page

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-co#29]
As a **Site Owner**, I can **redirect users to a customized 404 page** so that **I can keep them on my website and reduce their 'negative' experience**.

---
**Acceptance Criteria**
- [ ] **Given** that I navigate on the website, **when** an error 500 is raised, **then** I land on a customize 500 page with 
    - [ ] the company branding format
    - [ ] an explanation of the problem
    - [ ] apologies for the problem
    - [ ] a clear way back to the website
 
---
**Tasks**
- [ ] Create the content of the page
- [ ] Create the HTML & CSS
- [ ] Test the page:
    - [ ] Works properly when error 500 raised
    - [ ] Display right content with right style on any type of devices
    - [ ] Display right content with right style on any web browser
